# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Price(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, price: float=None):  # noqa: E501
        """Price - a model defined in Swagger

        :param price: The price of this Price.  # noqa: E501
        :type price: float
        """
        self.swagger_types = {
            'price': float
        }

        self.attribute_map = {
            'price': 'price'
        }
        self._price = price

    @classmethod
    def from_dict(cls, dikt) -> 'Price':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Price of this Price.  # noqa: E501
        :rtype: Price
        """
        return util.deserialize_model(dikt, cls)

    @property
    def price(self) -> float:
        """Gets the price of this Price.


        :return: The price of this Price.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this Price.


        :param price: The price of this Price.
        :type price: float
        """

        self._price = price
