openapi: 3.0.0
info:
  title: ethereum
  version: "1.0"
servers:
- url: http://localhost:3000
paths:
  /eth-price:
    get:
      tags: []
      summary: Your GET endpoint
      operationId: get_eth_price
      parameters:
      - name: price
        in: query
        description: current Ethereum price
        required: false
        style: form
        explode: true
        schema:
          type: number
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Price'
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /profitability:
    get:
      tags: []
      summary: Your GET endpoint
      operationId: get_profitability
      parameters:
      - name: profitability
        in: query
        description: profitability
        required: false
        style: form
        explode: true
        schema:
          type: number
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profitability'
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    GPU:
      title: GPU
      type: object
      properties:
        name:
          type: string
        power:
          type: number
        hash:
          type: number
    Price:
      title: Price
      type: object
      properties:
        price:
          type: number
      example:
        price: 0.80082819046101150206595775671303272247314453125
    Profitability:
      title: Profitability
      type: object
      properties:
        id:
          type: number
      example:
        id: 0.80082819046101150206595775671303272247314453125

